import typograph from '@tailwindcss/typography'
import defaultTheme from 'tailwindcss/defaultTheme'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./app/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Open Sans"', ...defaultTheme.fontFamily.sans],
      },
    },
    colors: {
      primary: '#5f57ff',
      danger: '#df1c41',
      gray: {
        1: 'var(--gray-1)',
        2: 'var(--gray-2)',
        3: 'var(--gray-3)',
        4: 'var(--gray-4)',
        5: 'var(--gray-5)',
        6: 'var(--gray-6)',
        7: 'var(--gray-7)',
        8: 'var(--gray-8)',
        9: 'var(--gray-9)',
        10: 'var(--gray-10)',
        11: 'var(--gray-11)',
        12: 'var(--gray-12)',
      },
      mauve: {
        1: 'var(--mauve-1)',
        2: 'var(--mauve-2)',
        3: 'var(--mauve-3)',
        4: 'var(--mauve-4)',
        5: 'var(--mauve-5)',
        6: 'var(--mauve-6)',
        7: 'var(--mauve-7)',
        8: 'var(--mauve-8)',
        9: 'var(--mauve-9)',
        10: 'var(--mauve-10)',
        11: 'var(--mauve-11)',
        12: 'var(--mauve-12)',
        a1: 'var(--mauve-a1)',
        a2: 'var(--mauve-a2)',
        a3: 'var(--mauve-a3)',
        a4: 'var(--mauve-a4)',
        a5: 'var(--mauve-a5)',
        a6: 'var(--mauve-a6)',
        a7: 'var(--mauve-a7)',
        a8: 'var(--mauve-a8)',
        a9: 'var(--mauve-a9)',
        a10: 'var(--mauve-a10)',
        a11: 'var(--mauve-a11)',
        a12: 'var(--mauve-a12)',
      },
      violet: {
        1: 'var(--violet-1)',
        2: 'var(--violet-2)',
        3: 'var(--violet-3)',
        4: 'var(--violet-4)',
        5: 'var(--violet-5)',
        6: 'var(--violet-6)',
        7: 'var(--violet-7)',
        8: 'var(--violet-8)',
        9: 'var(--violet-9)',
        10: 'var(--violet-10)',
        11: 'var(--violet-11)',
        12: 'var(--violet-12)',
      },
    },
    container: {
      center: true,
      padding: '1rem',
    },
    screens: {
      tablet: '768px',
      desktop: '1024px',
      large: '1280px',
    },
  },
  plugins: [typograph()],
}
